// <auto-generated />
using System;
using DataAccessLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f"),
                            Name = "PMP-41"
                        });
                });

            modelBuilder.Entity("TsukatTestTask.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9710de87-1ced-400a-8097-04339ef146e0"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TsukatTestTask.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasMaxLength(125);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a560c6f1-c54b-4a8b-a3e6-312215bce364"),
                            Age = 20,
                            Email = "stetskivostap@gmail.com",
                            GroupId = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f"),
                            Name = "Ostap",
                            Password = "yI6cZwQadOA1e+/f+T+H3eCQQhQ=",
                            RoleId = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f")
                        },
                        new
                        {
                            Id = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f"),
                            Age = 20,
                            Email = "stetskiv@gmail.com",
                            GroupId = new Guid("b2c16f3a-7531-4229-94ac-c89f5833c87f"),
                            Name = "Ostap",
                            Password = "yI6cZwQadOA1e+/f+T+H3eCQQhQ=",
                            RoleId = new Guid("9710de87-1ced-400a-8097-04339ef146e0")
                        });
                });

            modelBuilder.Entity("TsukatTestTask.Entities.User", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TsukatTestTask.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
